---
language: python

python:
  - "3.7"

services:
  - docker

env:
  matrix:
    - image="docker-alpine-openrc"
    - image="docker-alpine-openrc" tag="edge"
    # - namespace="archlinux/" image="base"
    - image="docker-debian-systemd" tag="stable"
    - image="docker-debian-systemd" tag="unstable"
    - image="docker-debian-systemd"
    - image="docker-centos-systemd"
    - image="docker-redhat-systemd"
    - image="docker-fedora-systemd"
    - image="docker-fedora-systemd" tag="rawhide"
    - image="docker-opensuse-systemd"
    - image="docker-ubuntu-systemd" tag="rolling"
    - image="docker-ubuntu-systemd" tag="devel"
    - image="docker-ubuntu-systemd"

matrix:
  allow_failures:
    - env: image="docker-alpine-openrc" tag="edge"
    - env: image="docker-debian-systemd" tag="unstable"
    - env: image="docker-fedora-systemd" tag="rawhide"
    - env: image="docker-ubuntu-systemd" tag="rolling"
    - env: image="docker-ubuntu-systemd" tag="devel"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "KNGb6nUiIFk86AMSfRdnFFWcKh4whVEcvS3ycBdhEBhbG4/4d8TBNFILjLpvTrr5d2Vmhj4JM2dRTwfkEj+ChC9cCknSVwkwZqbOx+H1NmiYgTWHn8Ar89NOh/GnaV3aU1AcK36L+7M9pcoTaLtl0BRWwrR4BUCIUFqgOf7vEtKWew+b1zmaGG3hygrGYFMKFJa4GfsGiSYnkn8TFG2muacgzlActQzML1xHrE/kR4hWK7dMZCLdPDgzXyRDwMZwkQQxPwKe0rCLYY7izzRoFchziyyvtwCrZ2F5sN4HsNploCwBRPCw3o6ZdhybPlmEls/PE+UhshV7NZb8t5/oX2bTHnHABEyRs6dLJotxgYCkkU4brlq2btWiYVP5FdCHYF/PraQbb5yNl+fKGSPimGj++B3MgIGLaq0ZskO3RC+RiqNnO5V6/SLjr4zk4JqPtPl7CEX3o77VcxQQEm91Xk7++yNCng8ShAK2IrBWxezQc4ZwyyvntNYi+ODqJaJDMCE+RQAaw1iBvGgaAX2P798LPJRew9D64xByC7FUKTe9TSOoYG635/iKWVDLneLd3CdvaKwkBSx2A/6eO6HGjSqi7PHhY1Y3Jru+oTVB3NNopHHLNNo2Qv1us76meP6LoxaoCvkt7/YmFkCYxvkCWey5q6vq0Kd0IhC3uGYFSkA="
  email: false
