---
#
# Ansible managed
#
language: python

python:
  - "3.7"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="debian" tag="latest"
    - image="debian" tag="testing"
    - image="debian" tag="unstable"
    - image="centos" tag="latest"
    - image="fedora" tag="30"
    - image="fedora" tag="latest"
    - image="fedora" tag="rawhide"
    - image="ubuntu" tag="latest"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "KNGb6nUiIFk86AMSfRdnFFWcKh4whVEcvS3ycBdhEBhbG4/4d8TBNFILjLpvTrr5d2Vmhj4JM2dRTwfkEj+ChC9cCknSVwkwZqbOx+H1NmiYgTWHn8Ar89NOh/GnaV3aU1AcK36L+7M9pcoTaLtl0BRWwrR4BUCIUFqgOf7vEtKWew+b1zmaGG3hygrGYFMKFJa4GfsGiSYnkn8TFG2muacgzlActQzML1xHrE/kR4hWK7dMZCLdPDgzXyRDwMZwkQQxPwKe0rCLYY7izzRoFchziyyvtwCrZ2F5sN4HsNploCwBRPCw3o6ZdhybPlmEls/PE+UhshV7NZb8t5/oX2bTHnHABEyRs6dLJotxgYCkkU4brlq2btWiYVP5FdCHYF/PraQbb5yNl+fKGSPimGj++B3MgIGLaq0ZskO3RC+RiqNnO5V6/SLjr4zk4JqPtPl7CEX3o77VcxQQEm91Xk7++yNCng8ShAK2IrBWxezQc4ZwyyvntNYi+ODqJaJDMCE+RQAaw1iBvGgaAX2P798LPJRew9D64xByC7FUKTe9TSOoYG635/iKWVDLneLd3CdvaKwkBSx2A/6eO6HGjSqi7PHhY1Y3Jru+oTVB3NNopHHLNNo2Qv1us76meP6LoxaoCvkt7/YmFkCYxvkCWey5q6vq0Kd0IhC3uGYFSkA="
  email: false
