---
# tasks file for ara
- name: install required packages
  package:
    name: "{{ ara_packages }}"
    state: present
  become: yes
  register: ara_install_required_packages
  until: ara_install_required_packages is succeeded
  retries: 3

- name: install ara
  pip:
    name: ara
    state: present
  become: yes
  register: ara_install_ara
  until: ara_install_ara is succeeded
  retries: 3

- name: create ara service
  import_role:
    name: robertdebock.service
  become: yes

- name: find callback_plugins path
  shell: "{{ ara_setup_command_python2 }} || {{ ara_setup_command_python3 }}"
  changed_when: no
  register: ara_callback_plugins

- name: configure ansible to use ara
  ini_file:
    path: "{{ ara_configuration_file }}"
    section: defaults
    option: callback_plugins
    value: "{{ ara_callback_plugins.stdout }}"
  notify:
    - restart ara
  when:
    - ara_configuration_file is defined
    - ara_callback_plugins.stdout is defined
  become: yes

- name: configure ara
  ini_file:
    path: "{{ ara_configuration_file }}"
    section: ara
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  notify:
    - restart ara
  with_items:
    - "{{ ara_configuration }}"
  when:
    - ara_configuration is defined
  loop_control:
    label: "{{ item.option }}"

- name: start and enable ara
  service:
    name: ara
    state: started
    enabled: yes
  when:
    - ansible_virtualization_type != "docker"
  become: yes
