---
# handlers file for ara
- name: restart ara
  service:
    name: ara
    state: restarted
  become: yes

- name: systemctl daemon-reload
  systemd:
    daemon_reload: yes
  become: yes
  notify:
    - restart ara
