---
# handlers file for ara
- name: restart ara
  service:
    name: ara
    state: restarted
  when:
    - ansible_virtualization_type != "docker"

- name: systemctl daemon-reload
  systemd:
    daemon_reload: yes
