---
# handlers file for ara
- name: restart ara
  service:
    name: ara
    state: restarted
  when:
    - ansible_virtualization_type != "docker"
  become: true

- name: systemctl daemon-reload
  systemd:
    daemon_reload: yes
  become: true
